on:
  push:
    branches: master
    
jobs: 
  auto-test:
     name: Automatic Jest run
     runs-on: [ubuntu-18.04]
     steps:
       - name: Install dependencies
         run: yarn install
       - name: Run Jest
         run: jest
