name: master

on: [push, pull_request]
    
jobs: 
  auto-test:
     name: Automatic Jest run
     runs-on: [ubuntu-16.04]
     steps:
       - uses: /actions/checkout@v1
       - name: Install dependencies
         run: yarn install
       - name: Run test
         run: yarn test-ci
