name: master

on: [push, pull_request]
    
jobs: 
  auto-test:
     name: Automatic Jest run
     runs-on: [ubuntu-16.04]
     steps:
       - uses: /actions/checkout@v1
       - name: Install dependencies
         run: yarn install
       - name: Configure Git
         run: git config --global user.email "316413310@qq.com" && git config --global user.name "Soulike"
       - name: Run test
         run: yarn ci
